# Keep GitHub Actions scheduled workflows alive.
name: keep_alive

on:
  workflow_dispatch:
  schedule:
     - cron: '20 0 1 * *'

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Keep cronjob based triggers of GitHub workflows alive
        uses: PhrozenByte/gh-workflow-immortality@v1
        with:
          secret: ${{ secrets.KEEP_ALIVE_TOKEN }}
          repos: |
            ${{ github.repository }}
            ${{ github.repository_owner }}/community
            ${{ github.repository_owner }}/r-multiverse.github.io
            ${{ github.repository_owner }}/staging
            ${{ github.repository_owner }}/status
            ${{ github.repository_owner }}/topics
