name: review_pull_requests

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'

jobs:
  review_pull_requests:
    runs-on: macOS-latest

    steps:
      - name: Generate GitHub installation access token.
        uses: actions/create-github-app-token@v1.8.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Install R.
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install helper R package.
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(
            pkgs = "multiverse.internals",
            repos = c("https://${{ github.repository_owner }}.r-universe.dev", "https://cloud.r-project.org/"),
            type = "binary"
          )
        shell: Rscript {0}

      - name: Review pull requests
        env:
          GITHUB_PAT: ${{ steps.app-token.outputs.token }}
        run: |
          multiverse.internals::review_pull_requests(
            owner = "${{ github.repository_owner }}",
            repo = "contributions"
          )
        shell: Rscript {0}
