name: status
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  status:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libglpk-dev

      - name: Install R.
        uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: https://community.r-multiverse.org
          use-public-rspm: true

      - name: Install helper R package.
        run: |
          install.packages("pak")
          pak::pkg_install("r-multiverse/multiverse.internals@*release")
        shell: Rscript {0}

      - name: Check out the universe.
        uses: actions/checkout@v4

      - name: Record versions.
        run: |
          multiverse.internals::record_versions(
            versions = "versions.json",
            repo = "https://community.r-multiverse.org"
          )
        shell: Rscript {0}

      - name: Record status.
        run: |
          multiverse.internals::record_status(
            repo = "https://community.r-multiverse.org",
            versions = "versions.json",
            output = "status.json"
          )
        shell: Rscript {0}

      - name: Record non-standard licenses.
        run: |
          multiverse.internals::record_nonstandard_licenses(
            repo = "https://community.r-multiverse.org",
            path = "nonstandard_licenses.json"
          )
        shell: Rscript {0}

      - name: Commit and push changes.
        run: |
          git add *.json
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name github-actions
            git config --global user.email actions@github.com
            git commit -m "Update status"
            git push -u origin main
          fi
